### ISSUE TITLE
请问支持中文处理吗？

### ISSUE THREAD

**Issue by fishfree** [tanloong/neosca#46]
你们是否依赖于Penn Tree Bank? 非常谢谢！

**Comment by tanloong** [comment]
中文不支持，只支持英文。

SCA模块的指标专为英语设计，对中文不一定适合。导入文件会被当作英语，用Stanza的英语语种的模型做短语结构分析。

LCA模块指标不是只对英语有效，但程序没支持中文，文件还是会被全部当作英语用英语的模型做分词和词性标注、判断难词用的参照语料也是英语的BNC或ANC。

SCA模块所调用的Stanza的英语语种的短语结构分析器是基于宾州树库训练的，Stanza文档说[有一些改动](https://stanfordnlp.github.io/stanza/constituency.html#english)。
